//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ProjectApp.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_USER               101
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define ID_INDICATOR_TIME               126
#define ID_INDICATOR_SERVER             127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ProjectAppTYPE              130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_SETRFID_DIALOG              311
#define IDD_SETSTATION_DIALOG           313
#define IDD_SETCALLER_DIALOG            315
#define IDD_SETAGV_DIALOG               317
#define IDB_BITMAP1                     319
#define IDB_BITMAP2                     320
#define IDB_BITMAP3                     321
#define IDB_BITMAP4                     322
#define IDB_BITMAP5                     323
#define IDB_BITMAP6                     324
#define IDB_BITMAP7                     325
#define IDB_BITMAP8                     326
#define IDB_BITMAP9                     327
#define IDD_AGVSTATUS_DIALOG            328
#define IDD_CALLERSTATUS_DIALOG         330
#define IDD_STATIONCONFIG_DIALOG        332
#define IDD_TASK_DIALOG                 334
#define IDD_CREATETASK_DIALOG           336
#define IDD_USERLOGIN_DIALOG            338
#define IDD_ADDUSER_DIALOG              340
#define IDD_EDITUSER_DIALOG             342
#define IDD_DELUSER_DIALOG              344
#define IDC_RFIDNO_STATIC               1000
#define IDC_RFIDNO_EDIT                 1001
#define IDC_STATIONNO_STATIC            1002
#define IDC_STATIONNO_EDIT              1003
#define IDC_STATIONLOCATION_STATIC      1004
#define IDC_STATIONLOCATION_EDIT        1005
#define IDC_STATIONNAME_STATIC          1006
#define IDC_STATIONNAME_EDIT            1007
#define IDC_STATIONPROCESS_COMBO        1008
#define IDC_CALLERNO_STATIC             1009
#define IDC_CALLERNO_EDIT               1010
#define IDC_CALLERSTATION_EDIT2         1011
#define IDC_CALLERSTATION_EDIT          1011
#define IDC_CALLERSTATION_STATIC        1012
#define IDC_AGVNO_EDIT                  1013
#define IDC_CALLERSTATION_STATIC2       1013
#define IDC_AGVCLIENT_IPADDRESS         1014
#define IDC_MACADDRESS_EDIT             1014
#define IDC_AGVSERVERPORT_EDIT          1015
#define IDC_AGVSERVER_IPADDRESS         1016
#define IDC_EDIT3                       1018
#define IDC_AGVCLIENTPORT_EDIT          1018
#define IDC_SERVER_RADIO                1019
#define IDC_CLIENT_RADIO                1020
#define IDC_AGVCONFIG_LIST              1021
#define IDC_ADDAGV_BUTTON               1022
#define IDC_EDITAGV_BUTTON              1023
#define IDC_DELAGV_BUTTON               1024
#define IDC_AGVSTATUS_LIST              1025
#define IDC_CALLERSTATUS_LIST           1026
#define IDC_STATIONCONFIG_LIST          1027
#define IDC_TASK_LIST                   1028
#define IDC_CREATE_BUTTON               1029
#define IDC_CANCEL_BUTTON               1030
#define IDC_START_COMBO                 1032
#define IDC_END_COMBO                   1033
#define IDC_EXECUTER_COMBO              1034
#define IDC_TYPE_COMBO                  1035
#define IDC_MESWP_EDIT                  1036
#define IDC_MES_CHECK                   1038
#define IDC_USE_CHECK                   1039
#define IDC_EDIT_BUTTON                 1040
#define IDC_DEL_BUTTON                  1041
#define IDC_ENABLE_BUTTON               1042
#define IDC_DISABLE_BUTTON              1043
#define IDC_ALLENABLE_BUTTON            1044
#define IDC_ALLDISABLE_BUTTON           1045
#define IDC_USER_EDIT                   1046
#define IDC_PASSWORD_EDIT               1047
#define IDC_LEVEL_COMBO                 1048
#define IDC_COMFIRM_EDIT                1049
#define IDC_NEWPASSWORD_EDIT            1050
#define IDC_OLDPASSWORD_EDIT            1051
#define IDC_USER_COMBO                  1052
#define IDC_AGVNO_STATIC                1053
#define IDC_AGVNO_COMBO                 1054
#define IDC_AGVCTRL_STATIC              1055
#define IDC_AGVCTRL_COMBO               1056
#define IDC_TARGET_STATIC               1057
#define IDC_TARGET_COMBO                1058
#define IDC_EXE_BUTTON                  1059
#define IDC_CLEAR_BUTTON                1060
#define ID_TOOL_RFID                    32771
#define ID_TOOL_CHARGER                 32772
#define ID_TOOL_REST                    32773
#define ID_TOOL_STATION                 32774
#define ID_TRACK_LINE                   32775
#define ID_TRACK_ARC                    32776
#define ID_TOOL_TRACK_LINE              32778
#define ID_TOOL_TRACK_ARC               32779
#define ID_32780                        32780
#define ID_TOOL_CALLER                  32781
#define ID_MODE_EDIT                    32782
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_32785                        32785
#define ID_MODE_RUN                     32786
#define ID_32787                        32787
#define ID_MAP_SAVE                     32788
#define ID_32789                        32789
#define ID_USER_RELOGIN                 32790
#define ID_32791                        32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_USER_ADD                     32794
#define ID_USER_EDIT                    32795
#define ID_USER_DELETE                  32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
